// frontend/src/app/shared/components/navbar/navbar.component.ts
import { Component, inject } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { NgIf } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { AuthService } from '../../../core/auth/auth.service';
import { LanguageSwitcherComponent } from '../language-switcher/language-switcher.component';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, NgIf, TranslateModule, LanguageSwitcherComponent],
  template: `
    <nav class="sticky top-0 z-40 border-b border-[#E2E8F0] bg-white/80 backdrop-blur-md">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">

          <!-- Logo -->
          <a routerLink="/" class="flex items-center gap-2 font-bold text-xl text-[#2563EB] no-underline">
            <svg class="w-8 h-8" viewBox="0 0 32 32" fill="none">
              <rect width="32" height="32" rx="8" fill="currentColor" />
              <path d="M8 10h16M8 16h12M8 22h14" stroke="white" stroke-width="2.5" stroke-linecap="round" />
            </svg>
            DocMind
          </a>

          <!-- Desktop Nav -->
          <div class="hidden md:flex items-center gap-4">
            <app-language-switcher />

            <ng-container *ngIf="auth.isAuthenticated; else guestNav">
              <a routerLink="/dashboard" class="text-sm text-[#475569] hover:text-[#0F172A] transition-colors no-underline">
                {{ 'nav.dashboard' | translate }}
              </a>
              <a routerLink="/github/import" class="text-sm text-[#475569] hover:text-[#0F172A] transition-colors no-underline">
                {{ 'nav.github_import' | translate }}
              </a>
              <a *ngIf="auth.currentUser?.is_superuser" routerLink="/admin" class="text-sm text-[#475569] hover:text-[#0F172A] transition-colors no-underline">
                {{ 'nav.admin' | translate }}
              </a>

              <!-- User Menu -->
              <div class="relative" (clickOutside)="menuOpen = false">
                <button (click)="menuOpen = !menuOpen"
                        class="flex items-center gap-2 text-sm text-[#334155] hover:text-[#0F172A] cursor-pointer bg-transparent border-0">
                  <div class="w-8 h-8 rounded-full bg-[#DBEAFE] text-[#2563EB] flex items-center justify-center text-sm font-medium">
                    {{ (auth.currentUser?.display_name || 'U')[0].toUpperCase() }}
                  </div>
                  <span class="hidden lg:inline">{{ auth.currentUser?.display_name }}</span>
                </button>

                <div *ngIf="menuOpen" class="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-[#E2E8F0] py-1 z-50">
                  <a routerLink="/settings" (click)="menuOpen = false"
                     class="block px-4 py-2 text-sm text-[#334155] hover:bg-[#F8FAFC] no-underline">{{ 'nav.settings' | translate }}</a>
                  <hr class="border-[#F1F5F9]" />
                  <button (click)="logout(); menuOpen = false"
                          class="w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-[#F8FAFC] cursor-pointer bg-transparent border-0">
                    {{ 'nav.signOut' | translate }}
                  </button>
                </div>
                <div *ngIf="menuOpen" class="fixed inset-0 z-[-1]" (click)="menuOpen = false"></div>
              </div>
            </ng-container>

            <ng-template #guestNav>
              <a routerLink="/login"
                 class="text-sm text-[#475569] hover:text-[#0F172A] transition-colors no-underline">{{ 'nav.signIn' | translate }}</a>
              <a routerLink="/register"
                 class="inline-flex items-center h-9 px-4 rounded-lg text-sm font-medium text-white bg-[#2563EB] hover:bg-[#1D4ED8] transition-colors no-underline shadow-sm">
                {{ 'nav.getStarted' | translate }}
              </a>
            </ng-template>
          </div>

          <!-- Mobile Hamburger -->
          <button class="md:hidden text-[#475569] cursor-pointer bg-transparent border-0 p-1" (click)="menuOpen = !menuOpen" aria-label="Toggle menu">
            <svg class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path *ngIf="!menuOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
              <path *ngIf="menuOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <!-- Mobile Menu -->
        <div *ngIf="menuOpen" class="md:hidden border-t border-[#E2E8F0] py-4 space-y-2">
          <div class="px-3 py-2"><app-language-switcher /></div>
          <ng-container *ngIf="auth.isAuthenticated; else guestMobile">
            <a routerLink="/dashboard" (click)="menuOpen = false" class="block px-3 py-2 text-sm rounded-lg hover:bg-[#F8FAFC] no-underline text-[#334155]">{{ 'nav.dashboard' | translate }}</a>
            <a routerLink="/github/import" (click)="menuOpen = false" class="block px-3 py-2 text-sm rounded-lg hover:bg-[#F8FAFC] no-underline text-[#334155]">{{ 'nav.github_import' | translate }}</a>
            <a *ngIf="auth.currentUser?.is_superuser" routerLink="/admin" (click)="menuOpen = false" class="block px-3 py-2 text-sm rounded-lg hover:bg-[#F8FAFC] no-underline text-[#334155]">{{ 'nav.admin' | translate }}</a>
            <a routerLink="/settings" (click)="menuOpen = false" class="block px-3 py-2 text-sm rounded-lg hover:bg-[#F8FAFC] no-underline text-[#334155]">{{ 'nav.settings' | translate }}</a>
            <button (click)="logout(); menuOpen = false" class="w-full text-left px-3 py-2 text-sm text-red-600 rounded-lg hover:bg-[#F8FAFC] cursor-pointer bg-transparent border-0">{{ 'nav.signOut' | translate }}</button>
          </ng-container>
          <ng-template #guestMobile>
            <a routerLink="/login" (click)="menuOpen = false" class="block px-3 py-2 text-sm rounded-lg hover:bg-[#F8FAFC] no-underline text-[#334155]">{{ 'nav.signIn' | translate }}</a>
            <a routerLink="/register" (click)="menuOpen = false" class="block px-3 py-2 text-sm rounded-lg hover:bg-[#F8FAFC] no-underline text-[#334155]">{{ 'nav.getStarted' | translate }}</a>
          </ng-template>
        </div>
      </div>
    </nav>
  `,
})
export class NavbarComponent {
  readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  menuOpen = false;

  logout(): void { this.auth.logout(); }
}

// frontend/src/components/layout/Navbar.tsx
import { Link, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/contexts/AuthContext';
import Button from '@/components/ui/Button';
import LanguageSwitcher from '@/components/common/LanguageSwitcher';
import { useState } from 'react';

export default function Navbar() {
  const { t } = useTranslation();
  const { user, isAuthenticated, logout } = useAuth();
  const navigate = useNavigate();
  const [menuOpen, setMenuOpen] = useState(false);

  const handleLogout = async () => {
    await logout();
    navigate('/');
    setMenuOpen(false);
  };

  return (
    <nav className="sticky top-0 z-40 border-b border-surface-200 bg-white/80 backdrop-blur-md">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <Link to="/" className="flex items-center gap-2 font-bold text-xl text-primary-700">
            <svg className="w-8 h-8" viewBox="0 0 32 32" fill="none">
              <rect width="32" height="32" rx="8" fill="currentColor" className="text-primary-600" />
              <path d="M8 10h16M8 16h12M8 22h14" stroke="white" strokeWidth="2.5" strokeLinecap="round" />
            </svg>
            DocMind
          </Link>

          <div className="hidden md:flex items-center gap-4">
            <LanguageSwitcher />
            {isAuthenticated ? (
              <>
                <Link to="/dashboard" className="text-sm text-surface-600 hover:text-surface-900 transition-colors">
                  {t('nav.dashboard')}
                </Link>
                <Link to="/github/import" className="text-sm text-surface-600 hover:text-surface-900 transition-colors">
                  {t('nav.github_import')}
                </Link>
                {user?.is_superuser && (
                  <Link to="/admin" className="text-sm text-surface-600 hover:text-surface-900 transition-colors">
                    {t('nav.admin')}
                  </Link>
                )}
                <div className="relative">
                  <button
                    onClick={() => setMenuOpen(!menuOpen)}
                    className="flex items-center gap-2 text-sm text-surface-700 hover:text-surface-900 cursor-pointer"
                  >
                    <div className="w-8 h-8 rounded-full bg-primary-100 text-primary-700 flex items-center justify-center text-sm font-medium">
                      {user?.display_name?.[0]?.toUpperCase() || 'U'}
                    </div>
                    <span className="hidden lg:inline">{user?.display_name}</span>
                  </button>
                  {menuOpen && (
                    <>
                      <div className="fixed inset-0" onClick={() => setMenuOpen(false)} />
                      <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-surface-200 py-1 animate-in">
                        <Link to="/settings" className="block px-4 py-2 text-sm text-surface-700 hover:bg-surface-50" onClick={() => setMenuOpen(false)}>
                          {t('nav.settings')}
                        </Link>
                        <hr className="border-surface-100" />
                        <button onClick={handleLogout} className="w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-surface-50 cursor-pointer">
                          {t('nav.signOut')}
                        </button>
                      </div>
                    </>
                  )}
                </div>
              </>
            ) : (
              <>
                <Link to="/login">
                  <Button variant="ghost" size="sm">{t('nav.signIn')}</Button>
                </Link>
                <Link to="/register">
                  <Button size="sm">{t('nav.getStarted')}</Button>
                </Link>
              </>
            )}
          </div>

          <button className="md:hidden text-surface-600 cursor-pointer" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={menuOpen ? "M6 18L18 6M6 6l12 12" : "M4 6h16M4 12h16M4 18h16"} />
            </svg>
          </button>
        </div>

        {menuOpen && (
          <div className="md:hidden border-t border-surface-200 py-4 space-y-2 animate-in">
            <div className="px-3 py-2">
              <LanguageSwitcher />
            </div>
            {isAuthenticated ? (
              <>
                <Link to="/dashboard" className="block px-3 py-2 text-sm rounded-lg hover:bg-surface-50" onClick={() => setMenuOpen(false)}>{t('nav.dashboard')}</Link>
                <Link to="/github/import" className="block px-3 py-2 text-sm rounded-lg hover:bg-surface-50" onClick={() => setMenuOpen(false)}>{t('nav.github_import')}</Link>
                {user?.is_superuser && (
                  <Link to="/admin" className="block px-3 py-2 text-sm rounded-lg hover:bg-surface-50" onClick={() => setMenuOpen(false)}>{t('nav.admin')}</Link>
                )}
                <Link to="/settings" className="block px-3 py-2 text-sm rounded-lg hover:bg-surface-50" onClick={() => setMenuOpen(false)}>{t('nav.settings')}</Link>
                <button onClick={handleLogout} className="w-full text-left px-3 py-2 text-sm text-red-600 rounded-lg hover:bg-surface-50 cursor-pointer">{t('nav.signOut')}</button>
              </>
            ) : (
              <>
                <Link to="/login" className="block px-3 py-2 text-sm rounded-lg hover:bg-surface-50" onClick={() => setMenuOpen(false)}>{t('nav.signIn')}</Link>
                <Link to="/register" className="block px-3 py-2 text-sm rounded-lg hover:bg-surface-50" onClick={() => setMenuOpen(false)}>{t('nav.getStarted')}</Link>
              </>
            )}
          </div>
        )}
      </div>
    </nav>
  );
}
