// frontend/src/components/viewer/PdfViewer.tsx
import { useState, useEffect, useCallback, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import * as pdfjsLib from 'pdfjs-dist';

pdfjsLib.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.mjs',
  import.meta.url
).toString();

interface Props {
  docId: string;
}

export default function PdfViewer({ docId }: Props) {
  const { t } = useTranslation();
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [numPages, setNumPages] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [zoom, setZoom] = useState(1.0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const pdfDocRef = useRef<pdfjsLib.PDFDocumentProxy | null>(null);
  const renderTaskRef = useRef<pdfjsLib.RenderTask | null>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);

    const token = localStorage.getItem('access_token');
    fetch(`/api/v1/documents/${docId}/original`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load PDF (${res.status})`);
        return res.arrayBuffer();
      })
      .then((data) => pdfjsLib.getDocument({ data }).promise)
      .then((pdf) => {
        if (!cancelled) {
          pdfDocRef.current = pdf;
          setNumPages(pdf.numPages);
          setCurrentPage(1);
        }
      })
      .catch((err) => {
        if (!cancelled) setError(err.message);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
      if (renderTaskRef.current) renderTaskRef.current.cancel();
    };
  }, [docId]);

  useEffect(() => {
    const pdf = pdfDocRef.current;
    const canvas = canvasRef.current;
    if (!pdf || !canvas) return;

    let cancelled = false;

    pdf.getPage(currentPage).then((page) => {
      if (cancelled) return;
      const viewport = page.getViewport({ scale: zoom });
      canvas.width = viewport.width;
      canvas.height = viewport.height;

      if (renderTaskRef.current) renderTaskRef.current.cancel();
      renderTaskRef.current = page.render({ canvas, viewport });
      renderTaskRef.current.promise.then(() => {
        if (!cancelled) renderTaskRef.current = null;
      });
    });

    return () => {
      cancelled = true;
      if (renderTaskRef.current) renderTaskRef.current.cancel();
    };
  }, [currentPage, zoom]);

  const goTo = useCallback(
    (p: number) => {
      if (p >= 1 && p <= numPages) setCurrentPage(p);
    },
    [numPages]
  );

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-4">
        <div className="w-12 h-12 border-4 border-primary-200 border-t-primary-600 rounded-full animate-spin" />
        <p className="text-surface-500 text-sm">{t('common.loading')}</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-3 text-surface-500">
        <svg className="w-12 h-12" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
        </svg>
        <p className="text-sm">{error}</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-slate-100">
      {/* Toolbar */}
      <div className="flex items-center justify-center gap-3 px-4 py-2 border-b border-slate-200 bg-white">
        <button
          onClick={() => goTo(currentPage - 1)}
          disabled={currentPage <= 1}
          className="px-2 py-1 rounded text-sm text-slate-600 hover:bg-slate-100 disabled:opacity-30 cursor-pointer"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
        </button>
        <span className="text-sm font-medium text-slate-600 tabular-nums min-w-[4rem] text-center">
          {currentPage} / {numPages}
        </span>
        <button
          onClick={() => goTo(currentPage + 1)}
          disabled={currentPage >= numPages}
          className="px-2 py-1 rounded text-sm text-slate-600 hover:bg-slate-100 disabled:opacity-30 cursor-pointer"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
        </button>
        <div className="w-px h-5 bg-slate-300" />
        <button onClick={() => setZoom((z) => Math.max(0.5, z - 0.25))} disabled={zoom <= 0.5} className="px-2 py-1 rounded text-sm text-slate-600 hover:bg-slate-100 disabled:opacity-30 cursor-pointer">−</button>
        <span className="text-xs text-slate-500 w-12 text-center tabular-nums">{Math.round(zoom * 100)}%</span>
        <button onClick={() => setZoom((z) => Math.min(3, z + 0.25))} disabled={zoom >= 3} className="px-2 py-1 rounded text-sm text-slate-600 hover:bg-slate-100 disabled:opacity-30 cursor-pointer">+</button>
        <button onClick={() => setZoom(1)} className="px-2 py-1 rounded text-xs text-slate-500 hover:bg-slate-100 cursor-pointer">{t('editor.reset_zoom') ?? 'Reset'}</button>
      </div>

      {/* Canvas */}
      <div className="flex-1 overflow-auto p-4 flex justify-center">
        <canvas ref={canvasRef} className="shadow-lg" />
      </div>
    </div>
  );
}

// frontend/src/app/viewers/pdf-viewer.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import * as pdfjsLib from 'pdfjs-dist';

pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/6.0.227/pdf.worker.min.mjs';

@Component({
  selector: 'app-pdf-viewer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="bg-white rounded-lg border border-gray-200 overflow-hidden">
      <div class="flex items-center justify-between p-3 bg-gray-50 border-b">
        <h3 class="font-semibold text-gray-800">PDF Preview</h3>
        <div class="flex items-center gap-2">
          <button class="px-3 py-1 text-sm bg-white border rounded hover:bg-gray-100 disabled:opacity-50"
                  [disabled]="currentPage <= 1" (click)="prevPage()">
            Previous
          </button>
          <span class="text-sm text-gray-600">Page {{ currentPage }} / {{ totalPages || '?' }}</span>
          <button class="px-3 py-1 text-sm bg-white border rounded hover:bg-gray-100 disabled:opacity-50"
                  [disabled]="currentPage >= totalPages" (click)="nextPage()">
            Next
          </button>
        </div>
      </div>
      <div class="flex items-center justify-center p-4 bg-gray-100 min-h-[500px]">
        <canvas #pdfCanvas class="max-w-full shadow-lg rounded"></canvas>
        <div *ngIf="!totalPages" class="text-gray-400 text-center">
          <span class="material-icons text-6xl mb-2">picture_as_pdf</span>
          <p>PDF preview not available</p>
        </div>
      </div>
    </div>
  `,
})
export class PdfViewerComponent implements OnChanges {
  @Input() pdfUrl: string | null = null;

  currentPage = 1;
  totalPages = 0;
  private pdfDoc: any = null;

  constructor() {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['pdfUrl'] && this.pdfUrl) {
      this.loadPdf();
    }
  }

  async loadPdf(): Promise<void> {
    try {
      this.pdfDoc = await pdfjsLib.getDocument(this.pdfUrl!).promise;
      this.totalPages = this.pdfDoc.numPages;
      this.currentPage = 1;
      this.renderPage();
    } catch (err) {
      console.error('PDF load error:', err);
    }
  }

  async renderPage(): Promise<void> {
    if (!this.pdfDoc) return;
    const page = await this.pdfDoc.getPage(this.currentPage);
    const canvas = document.querySelector('canvas') as HTMLCanvasElement;
    if (!canvas) return;
    const viewport = page.getViewport({ scale: 1.5 });
    canvas.height = viewport.height;
    canvas.width = viewport.width;
    const ctx = canvas.getContext('2d')!;
    await page.render({ canvasContext: ctx, viewport }).promise;
  }

  prevPage(): void {
    if (this.currentPage <= 1) return;
    this.currentPage--;
    this.renderPage();
  }

  nextPage(): void {
    if (this.currentPage >= this.totalPages) return;
    this.currentPage++;
    this.renderPage();
  }
}
