// frontend/src/app/viewers/pptx-viewer.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../core/http/api.service';
import type { SlideData, SlidesResponse } from '../shared/models/types';

@Component({
  selector: 'app-pptx-viewer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="bg-white rounded-lg border border-gray-200 overflow-hidden">
      <div class="flex items-center justify-between p-3 bg-gray-50 border-b">
        <h3 class="font-semibold text-gray-800">PPTX Preview</h3>
        <div class="flex items-center gap-2">
          <button class="px-3 py-1 text-sm bg-white border rounded hover:bg-gray-100 disabled:opacity-50"
                  [disabled]="currentSlide <= 0" (click)="prevSlide()">
            Previous
          </button>
          <span class="text-sm text-gray-600">Slide {{ currentSlide + 1 }} / {{ slides.length || '?' }}</span>
          <button class="px-3 py-1 text-sm bg-white border rounded hover:bg-gray-100 disabled:opacity-50"
                  [disabled]="currentSlide >= slides.length - 1" (click)="nextSlide()">
            Next
          </button>
        </div>
      </div>

      <div class="p-4 bg-gray-100 min-h-[500px]">
        <!-- Loading -->
        <div *ngIf="loading" class="flex items-center justify-center h-[500px]">
          <div class="animate-spin w-8 h-8 border-4 border-blue-200 border-t-blue-600 rounded-full"></div>
        </div>

        <!-- Error -->
        <div *ngIf="error" class="flex flex-col items-center justify-center h-[500px] text-red-400">
          <span class="material-icons text-6xl mb-2">error</span>
          <p>{{ error }}</p>
        </div>

        <!-- Slide display -->
        <div *ngIf="!loading && !error && currentSlideData" class="max-w-4xl mx-auto">
          <div class="bg-white rounded-lg shadow-lg overflow-hidden"
               [style.aspect-ratio]="slideAspectRatio">
            <div class="p-6 h-full overflow-auto">
              <div *ngFor="let shape of currentSlideData.shapes" class="mb-3">
                <!-- Title -->
                <h2 *ngIf="shape.is_title" class="text-2xl font-bold mb-4"
                    [style.color]="shape.font_color"
                    [style.text-align]="shape.alignment">
                  {{ shape.text }}
                </h2>
                <!-- Text shape -->
                <div *ngIf="!shape.is_title && shape.text && !shape.table_data"
                     [style.color]="shape.font_color"
                     [style.font-size.px]="shape.font_size"
                     [style.font-weight]="shape.font_bold ? 'bold' : 'normal'"
                     [style.font-style]="shape.font_italic ? 'italic' : 'normal'"
                     [style.text-align]="shape.alignment"
                     [style.background-color]="shape.fill_color || 'transparent'">
                  <p *ngFor="let para of shape.paragraphs" class="mb-1"
                     [style.text-align]="para.alignment"
                     [style.padding-left.px]="para.level * 20">
                    {{ para.text }}
                  </p>
                </div>
                <!-- Table -->
                <table *ngIf="shape.table_data" class="w-full border-collapse border border-gray-300">
                  <tbody>
                    <tr *ngFor="let row of shape.table_data.rows; let ri = index">
                      <td *ngFor="let cell of row; let ci = index"
                          class="border border-gray-300 p-2 text-sm"
                          [style.font-weight]="ri < shape.table_data.header_count ? 'bold' : 'normal'"
                          [style.background-color]="ri < shape.table_data.header_count ? '#f3f4f6' : 'white'">
                        {{ cell }}
                      </td>
                    </tr>
                  </tbody>
                </table>
                <!-- Image placeholder -->
                <div *ngIf="shape.has_image"
                     class="bg-gray-200 rounded flex items-center justify-center p-4 text-gray-500">
                  <span class="material-icons mr-2">image</span>
                  Image {{ shape.image_index }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class PptxViewerComponent implements OnChanges {
  @Input() docId: string | null = null;

  slides: SlideData[] = [];
  currentSlide = 0;
  loading = false;
  error: string | null = null;

  constructor(private api: ApiService) {}

  get currentSlideData(): SlideData | null {
    return this.slides[this.currentSlide] || null;
  }

  get slideAspectRatio(): string {
    const s = this.currentSlideData;
    if (!s || !s.height_px) return '16 / 9';
    return `${s.width_px} / ${s.height_px}`;
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['docId'] && this.docId) {
      this.loadSlides();
    }
  }

  loadSlides(): void {
    if (!this.docId) return;
    this.loading = true;
    this.error = null;
    this.api.getSlides(this.docId).subscribe({
      next: (res) => {
        this.loading = false;
        if (res.success && res.data) {
          this.slides = res.data.slides;
          this.currentSlide = 0;
        }
      },
      error: (err) => {
        this.loading = false;
        this.error = 'Failed to load slides: ' + (err.message || 'Unknown error');
      },
    });
  }

  prevSlide(): void {
    if (this.currentSlide > 0) this.currentSlide--;
  }

  nextSlide(): void {
    if (this.currentSlide < this.slides.length - 1) this.currentSlide++;
  }
}

// frontend/src/components/document/PptxViewer.tsx
import { useState, useEffect, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { slideApi } from '@/lib/api';
import type { ApiResponse, SlidesResponse, SlideData, SlideShape, SlideParagraph } from '@/types';

interface Props {
  docId: string;
}

function ShapeImage({ docId, slideIdx, imageIdx, maxW, maxH }: {
  docId: string; slideIdx: number; imageIdx: number; maxW: number; maxH: number;
}) {
  const [url, setUrl] = useState<string | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    let cancelled = false;
    slideApi.getSlideImage(docId, slideIdx, imageIdx)
      .then(({ data }) => {
        if (!cancelled) {
          const blobUrl = URL.createObjectURL(data as Blob);
          setUrl(blobUrl);
        }
      })
      .catch(() => { if (!cancelled) setError(true); });
    return () => {
      cancelled = true;
      if (url) URL.revokeObjectURL(url);
    };
  }, [docId, slideIdx, imageIdx]);

  if (error) {
    return (
      <div className="flex items-center justify-center bg-surface-100 text-surface-400 text-xs"
        style={{ width: maxW, height: maxH }}>
        [Image]
      </div>
    );
  }

  if (!url) {
    return (
      <div className="flex items-center justify-center bg-surface-100 animate-pulse"
        style={{ width: maxW, height: maxH }}>
        <div className="w-8 h-8 bg-surface-200 rounded" />
      </div>
    );
  }

  return (
    <img
      src={url}
      alt="slide image"
      style={{ maxWidth: maxW, maxHeight: maxH, objectFit: 'contain' }}
    />
  );
}

function RichParagraph({ p, defaultFontSize }: { p: SlideParagraph; defaultFontSize: number }) {
  if (!p.runs || p.runs.length === 0) {
    if (!p.text) return null;
    return (
      <p style={{
        textAlign: p.alignment as 'left' | 'center' | 'right' | 'justify',
        fontSize: defaultFontSize,
        margin: 0,
        lineHeight: 1.5,
      }}>
        {p.text}
      </p>
    );
  }

  return (
    <p style={{
      textAlign: p.alignment as 'left' | 'center' | 'right' | 'justify',
      fontSize: defaultFontSize,
      margin: 0,
      lineHeight: 1.5,
    }}>
      {p.runs.map((r, i) => (
        <span
          key={i}
          style={{
            fontWeight: r.bold ? 700 : 400,
            fontStyle: r.italic ? 'italic' : 'normal',
            fontSize: r.font_size ?? defaultFontSize,
            color: r.color?.startsWith('#') ? r.color : undefined,
            fontFamily: r.font_name ?? undefined,
          }}
        >
          {r.text}
        </span>
      ))}
    </p>
  );
}

function SlideRenderer({ slide, docId }: { slide: SlideData; docId: string }) {
  const scaleFactor = Math.min(1, 960 / slide.width_px);
  const w = slide.width_px * scaleFactor;
  const h = slide.height_px * scaleFactor;

  return (
    <div
      className="relative bg-white shadow-lg ring-1 ring-black/5 mx-auto"
      style={{ width: w, height: h, overflow: 'hidden' }}
    >
      {slide.shapes.map((shape) => (
        <ShapeElement key={shape.shape_idx} shape={shape} docId={docId} slideIdx={slide.slide_index} scaleFactor={scaleFactor} />
      ))}
    </div>
  );
}

function ShapeElement({ shape, docId, slideIdx, scaleFactor }: {
  shape: SlideShape; docId: string; slideIdx: number; scaleFactor: number;
}) {
  const l = shape.left * scaleFactor;
  const t = shape.top * scaleFactor;
  const w = shape.width * scaleFactor;
  const h = shape.height * scaleFactor;

  const style: React.CSSProperties = {
    position: 'absolute',
    left: l,
    top: t,
    width: w,
    height: h,
    padding: shape.shape_type === 'text' ? '2px 4px' : 0,
    overflow: 'hidden',
    wordBreak: 'break-word',
  };

  switch (shape.shape_type) {
    case 'picture':
      return (
        <div style={style}>
          <ShapeImage docId={docId} slideIdx={slideIdx} imageIdx={shape.image_index!} maxW={w} maxH={h} />
        </div>
      );

    case 'table':
      return (
        <div style={{ ...style, overflow: 'auto' }}>
          {shape.table_rows && (
            <table className="w-full border-collapse text-[10px]">
              <tbody>
                {shape.table_rows.map((row, ri) => (
                  <tr key={ri}>
                    {row.map((cell, ci) => (
                      <td key={ci} className="border border-surface-300 px-1 py-0.5">
                        {cell}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      );

    case 'text':
    default: {
      if (shape.fill_color) {
        style.backgroundColor = shape.fill_color;
      }
      const fontSize = (shape.font_size ?? 14) * scaleFactor;

      return (
        <div style={style}>
          {shape.paragraphs.length > 0 ? (
            shape.paragraphs.map((p, pi) => (
              <RichParagraph key={pi} p={p} defaultFontSize={fontSize} />
            ))
          ) : shape.text ? (
            <p style={{
              fontSize,
              fontWeight: shape.font_bold ? 700 : 400,
              fontStyle: shape.font_italic ? 'italic' : 'normal',
              color: shape.font_color?.startsWith('#') ? shape.font_color : undefined,
              fontFamily: shape.font_name ?? undefined,
              textAlign: (shape.alignment as 'left' | 'center' | 'right' | 'justify') || 'left',
              margin: 0,
              lineHeight: 1.5,
            }}>
              {shape.text}
            </p>
          ) : null}
        </div>
      );
    }
  }
}

export default function PptxViewer({ docId }: Props) {
  const { t } = useTranslation();
  const [slides, setSlides] = useState<SlideData[]>([]);
  const [currentSlide, setCurrentSlide] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    slideApi.getSlides(docId)
      .then(({ data }) => {
        const res = data as ApiResponse<SlidesResponse>;
        if (res.data?.slides) {
          setSlides(res.data.slides);
          setCurrentSlide(0);
        }
      })
      .catch((err) => {
        setError(err?.response?.data?.detail || err?.message || 'Failed to load slides');
      })
      .finally(() => setLoading(false));
  }, [docId]);

  const goTo = useCallback((idx: number) => {
    if (idx >= 0 && idx < slides.length) setCurrentSlide(idx);
  }, [slides.length]);

  const handleKeyDown = useCallback((e: KeyboardEvent) => {
    if (e.key === 'ArrowLeft') goTo(currentSlide - 1);
    else if (e.key === 'ArrowRight') goTo(currentSlide + 1);
  }, [currentSlide, goTo]);

  useEffect(() => {
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleKeyDown]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-4">
        <div className="w-12 h-12 border-4 border-primary-200 border-t-primary-600 rounded-full animate-spin" />
        <p className="text-surface-500 text-sm">{t('common.loading')}</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-3 text-surface-500">
        <svg className="w-12 h-12" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
        </svg>
        <p className="text-sm">{error}</p>
      </div>
    );
  }

  if (slides.length === 0) {
    return (
      <div className="flex items-center justify-center h-full text-surface-400 text-sm">
        {t('editor.no_slides') ?? 'No slides found'}
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full">
      {/* Slide area */}
      <div className="flex-1 overflow-auto bg-surface-100 p-6 flex items-start justify-center">
        <SlideRenderer slide={slides[currentSlide]} docId={docId} />
      </div>

      {/* Navigation bar */}
      <div className="flex items-center justify-between px-4 py-3 border-t border-surface-200 bg-white">
        <button
          onClick={() => goTo(currentSlide - 1)}
          disabled={currentSlide === 0}
          className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-sm font-medium text-surface-700 hover:bg-surface-100 disabled:opacity-30 disabled:cursor-default transition-colors cursor-pointer"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          {t('editor.prev')}
        </button>

        <div className="flex items-center gap-2">
          <span className="text-sm text-surface-600">
            {currentSlide + 1} / {slides.length}
          </span>
          <select
            value={currentSlide}
            onChange={(e) => goTo(Number(e.target.value))}
            className="text-sm border border-surface-300 rounded-lg px-2 py-1 focus:outline-none focus:ring-2 focus:ring-primary-500"
          >
            {slides.map((_, i) => (
              <option key={i} value={i}>
                Slide {i + 1}
              </option>
            ))}
          </select>
        </div>

        <button
          onClick={() => goTo(currentSlide + 1)}
          disabled={currentSlide >= slides.length - 1}
          className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-sm font-medium text-surface-700 hover:bg-surface-100 disabled:opacity-30 disabled:cursor-default transition-colors cursor-pointer"
        >
          {t('editor.next')}
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
        </button>
      </div>
    </div>
  );
}
